### ISSUE TITLE
License appears to be missing

### ISSUE THREAD

**Issue by euank** [brhoades/pasty-http-client#9]
There is neither a license file nor a licence key in `package.json`.

**Comment by brhoades** [comment]
I've been procrastinating on making a decision with this. I'll try to make one before my next commit.

**Comment by brhoades** [comment]
@linuxmercedes @euank recommendations? I'm thinking GPL for all the pasty components.

**Comment by euank** [comment]
IMO GPLv3, AGPL, and Apache 2 are the options to pick between. I'd probably personally go with GPLv3.

Note that you may get fewer contributors/users/deployments if you pick GPL since companies (and some people) are mildly allergic to it.

**Comment by LinuxMercedes** [comment]
I'd recommend in favor of AGPL here because this is meant to be served over
a network. However, if you want to go that route you should check on the
compliance requirements--as I understand it, AGPL is somewhat picky about
that sort of thing.

**Comment by brhoades** [comment]
Added AGPL3 for pasty-core, pasty-http-client, and pasty-server.
